spring:
  jpa:
    properties_hibernate_dialect: org.hibernate.dialect.H2Dialect
  application:
    name: lab

  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always